# Generated by Django 6.0 on 2025-12-31 10:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_id', models.UUIDField()),
                ('aggregate_type', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'shared_outbox_event',
                'indexes': [models.Index(fields=['status', 'created_at'], name='shared_outb_status_fe1d9d_idx'), models.Index(fields=['event_type'], name='shared_outb_event_t_acdcdf_idx')],
            },
        ),
    ]
