# Generated by Django 6.0 on 2026-01-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outboxevent',
            name='version',
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='event_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
