# Generated by Django 6.0 on 2025-12-23 07:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("seller_id", models.UUIDField()),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ProductOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                ("published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "product_outbox",
                "indexes": [
                    models.Index(
                        fields=["published", "created_at"],
                        name="product_out_publish_6d4f77_idx",
                    )
                ],
            },
        ),
    ]
